### ISSUE TITLE
Duplicate of icon file

### ISSUE THREAD

**Issue by typoman** [roboDocs/rf-extension-boilerplate#3]
Is there any reason there is a duplicate of icon file? One is used for the Mechanic in the root but it's also in the resources folder. I'm confused on which one is used for what reason. Which one should I keep?

**Comment by gferreira** [comment]
hello @typoman,

these two images serve different purposes:

- `myExtensionMechanicIcon.png` is the icon for the Mechanic UI  
    it’s referenced in `myExtension.mechanic`  
   (see [Extension Item Format > icon](https://robofont.com/documentation/extensions/extension-item-format/))

- `source/resources/icon.png` is the icon for the built extension package
    it’s used by `build.py`  
    (see [ExtensionBundle.icon](https://robofont.com/documentation/building-tools/api/mojo/mojo-extensions/#mojo.extensions.icon))

it feels redundant in the boilerplate extension because both icons look the same. but you could have a different image for each icon, or have one icon and not the other…

you can of course delete one of the icons, and update the mechanic file or the build script so it points to the other one.

hope this makes sense!

**Comment by typoman** [comment]
I see! Thank you Gustavo. I only remembered seeing icons in Mechanic. I had no idea there is an icon displayed elsewhere.
